pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp Webmapping/index.html public/
    - cp Webmapping/ICU_30m_0.png public/
    - cp Webmapping/icu_communes_0.js public/
    - cp Webmapping/icu_pop_insee_stat_0.js public/
    - cp Webmapping/icu_pop_insee_stat_014.js public/
    - cp Webmapping/vue_temperature_moyenne_communes_0.js public/
  artifacts:
    paths:
      - public
  only:
    - main